[package]
name = "actix-web-validator"
version = "2.0.1-alpha.0"
authors = ["Belousow Makc <lib.bmw@gmail.com>", "Andrey Ermilov <andrerm@ya.ru>", "Kolomatskiy Artem <kolomatskiy@bk.ru>"]
edition = "2018"
description = "Validation mechanism for actix-web"
keywords = ["actix-web", "serialization", "querystring", "validator", "validation"]
categories = ["encoding", "web-programming"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rambler-digital-solutions/actix-web-validator"
documentation = "https://docs.rs/actix-web-validator/"

[dependencies]
actix-web = "3"
derive_more = "0.99"
validator = "0.11"
validator_derive = "0.11"
serde = "1"
serde_urlencoded = "0.7"
serde_json = "1"
log = "0.4"
futures = "0.3"
mime = "0.3"
bytes = "0.5"
actix-router = "0.2"
futures-util = "0.3"

[dev-dependencies]
actix-service = "1"
serde_derive = "1"
actix-rt = "1"
